language: ruby
script: rake rspec
rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head
notifications:
  email:
    - ndushay@stanford.edu
    - laneymcg@stanford.edu
    - jkeck@stanford.edu
    - bess@stanford.edu
